# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fopost < Formula
  desc "Schedule and publish social media content from your terminal"
  homepage "https://fopost.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.0/fopost_0.1.0_darwin_amd64.tar.gz"
      sha256 "1b09142b607d053b360c196abfed467816f5213d65599445a850ccc6404dce0c"

      def install
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.0/fopost_0.1.0_darwin_arm64.tar.gz"
      sha256 "12d84fd03272c0885a68ae491f8cecbcdc416b018253a4cbdc4c106bc3edb08d"

      def install
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.0/fopost_0.1.0_linux_amd64.tar.gz"
      sha256 "c4d8711e2c567510f20245ea6ffe55b9d8006f24ec2e9f791af9d57a18009b4c"

      def install
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.0/fopost_0.1.0_linux_arm64.tar.gz"
      sha256 "fc5c88ef04449821d299a2ea634a22b0ce11f37d7d095223a2acff25a9c18584"

      def install
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
  end

  test do
    system "#{bin}/fopost", "version"
  end
end
