# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fopost < Formula
  desc "Schedule and publish social media content from your terminal"
  homepage "https://fopost.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.1/fopost_0.1.1_darwin_amd64.tar.gz"
      sha256 "dfcf0f147bf6e7d54f792361a65da0095d5718a3cd513bd73b7fc06ebda48f21"

      define_method(:install) do
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.1/fopost_0.1.1_darwin_arm64.tar.gz"
      sha256 "f9977a3d1a6e7916c97982f9b55e20ee59a0642d3611740b9f03e374dc2fe1ce"

      define_method(:install) do
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.1/fopost_0.1.1_linux_amd64.tar.gz"
      sha256 "34f7fdb9b72eb86fd42d7840fbc493792b904b4de9f8c6d44a1f1af05312ff01"
      define_method(:install) do
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fopost/fopost-cli/releases/download/v0.1.1/fopost_0.1.1_linux_arm64.tar.gz"
      sha256 "5607d765751531c62a2e5fa5207f909c0b1a195de2f6b9eb3dc9e18597a5f655"
      define_method(:install) do
        bin.install "fopost"
        generate_completions_from_executable(bin/"fopost", "completion")
      end
    end
  end

  test do
    system "#{bin}/fopost", "version"
  end
end
